### ISSUE TITLE
IdentifyAsync will hang often

### ISSUE THREAD

**Issue by molnarr2** [launchdarkly/xamarin-client-sdk#7]
Switching to a new user will sometimes hang within this code:

`User user = User.WithKey(userKey);
await LdClient.Instance.IdentifyAsync(user);`

The userKey is a test username or blank for a default user.

This is within a fresh test app on iOS and using the following to initialize the client.

`User user = User.WithKey(userkey);
LdClient ldClient = LdClient.Init(sdkKey, user);`

**Comment by eli-darkly** [comment]
This issue referred to an early prerelease version of the SDK. We believe that the instability was eliminated prior to the 1.0.0 release. Please feel free to reopen the issue if you have seen it since then.
